name: Format and Deployment
on: push
jobs:
  eslint:
    name: Run Eslint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: install dependencies
      run: npm install
    - uses: actions/checkout@v1
    - uses: stefanoeb/eslint-action@1.0.2
      with:
        files: src/

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Production
    needs: eslint
    steps:  
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Run json-server
      run: npm run backend &
    - name: Build vue app
      run: npm run build
    - name: Deploy to GH-page
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
